version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mk_vsp_tg_bot
      POSTGRES_USER: mk_vsp_tg
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mk_vsp_tg_redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Moscow

  bot:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_URL: postgresql+asyncpg://mk_vsp_tg:1234@db:5432/mk_vsp_tg_bot
      ALEMBIC_DB_URL: postgresql+psycopg2://mk_vsp_tg:1234@db:5432/mk_vsp_tg_bot
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    volumes:
      - ./photos:/app/photos
    command: ["python", "main.py"]

volumes:
  pgdata:
